spring:
  application:
    name: UserService

  datasource:
    url: ${POSTGRES_URL_DOCKER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: redis
      port: 6379
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8081
